[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Optional: Add basic auth for private team use
# [context.production]
#   environment = { ACCESS_TOKEN = "your-secret-token" }