version: '3.8'

services:
  document-synthesizer:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Optional: Add a reverse proxy for multiple instances
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - document-synthesizer
    profiles:
      - proxy